### ISSUE TITLE
Ubuntu 22.04: error: ordered comparison of pointer with integer zero (‘widget*’ and ‘int’)

### ISSUE THREAD

**Issue by faveoled** [ericwomer/dangerdeep#1]
https://github.com/ericwomer/dangerdeep/blob/00a44e4ba90e7683e43cb2b4e431d9c7c4c8c338/src/widget.cpp#L287
Compiling on Ubuntu 22.04 produces this error:
```
/home/user/dangerdeep/src/widget.cpp: In member function ‘widget* widget::get_child(const string&, bool)’:
/home/user/dangerdeep/src/widget.cpp:287:34: error: ordered comparison of pointer with integer zero (‘widget*’ and ‘int’)
  287 |                         if(retval>0) return retval;
      |                            ~~~~~~^~
/home/user/dangerdeep/src/widget.cpp: At global scope:
```

**Comment by ericwomer** [comment]
Workaround applied in commit #442dad7, I haven't touched this code in over 5 years, but there is a lot of other bad code in this project, outdated c++ standards, and numerous other issues, good luck.
